global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "consume_service"
    static_configs:
      - targets: ["consume_service:2112"]

  - job_name: "api_service"
    static_configs:
      - targets: ["api:5000"]
